### PR TITLE
Fix building 4.x kernels in Vagrant

### PR DESCRIPTION
**Pull request by conorsch**
Due to a bug in `kernel-package` in Ubuntu 14.04 LTS (see #30 for details), we can't use `make-kpkg` to build 4.x Linux kernels with stable, non-backported distribution packages. Rather than fight over the meaning of LTS, we can simply switch the Vagrant base box for the `grsec-build` host to use `ubuntu/vivid64` rather than `ubuntu/trusty64`. Some minor packages changes result.

_Not_ included in this PR is a set of Ansible tasks to validate the OS under which the build is happening and scream bloody murder if 14.04 is detected. Happy to add such features to this PR, or they can be handled separately.

### CODE REVIEW

**Comment by conorsch** [comment]
Over the next few days, I'll script some build-and-install runs in Vagrant (rather than cloud providers) and report back with detailed results. Using the `manual` build strategy slows down the testing procedure a bit, but better safe than sorry.

**Comment by garrettr** [comment]
I took the same approach (using vivid for the 4.2.x kernels) in my personal repo, and it works. The only downside is that `kernel-package` pulled in about 80MB of dependencies on Trusty, but pulls in about **_1.5GB**_ of dependencies on Vivid. This is only annoying during the initial provisioning, but it is _really_ annoying, and also unnecessary - the bulk of those dependencies is LaTeX, which I'm sure is nice to have for something (?) but is completely unnecessary for us to build kernels.

I'd say we can live with this behavior for now, but it might be worth documenting it (so people who do this aren't like "wtf, why is this provision taking an hour?!?"), and maybe filing a follow-up issue to revisit this at a later date.

**Comment by conorsch** [comment]
Testing in vivid shows close to, but under, a gig download:

```
0 upgraded, 121 newly installed, 0 to remove and 0 not upgraded.
Need to get 779 MB of archives.
After this operation, 1,326 MB of additional disk space will be used.
```

Of course, that download size doubles once unpacked. Let me know if you see different sizes, but yes, that's a lot of data. We should definitely document a dependency of "about 20GB free disk space" in the README, accounting for the kernel build.

**Comment by garrettr** [comment]
Sorry, you're right - I was remembering the unpacked size rather than the download size. Still a lot though!

**Comment by garrettr** [comment]
We should definitely document the disk space requirement, and I would personally add a note saying that the kernel build requires a lot of dependencies, so the initial provisioning might take a while to download them all. Just so it's not a surprise.

**Comment by garrettr** [comment]
@conorsch You should either update the docs as suggested in https://github.com/freedomofpress/grsec/pull/32#issuecomment-163751291, or file a follow-up issue to do so, and then this can be merged.

**Comment by garrettr** [comment]
I have a PR that's waiting on this and brings in a bunch of improvements to the README, so if you file a follow-up issue for the docs I can take care of it in my PR.

**Comment by conorsch** [comment]
Update: building 4.x kernels in Vivid works great. Also tested installing the 4.x deb packages in:
- `ubuntu/trusty64`
- `ubuntu/vivid64`
- `debian/wheezy64`
- `debian/jessie64`

Wheezy threw an error because `paxtest` isn't available in the repos. We're requiring `paxtest` to be installed, but not actually using the package anywhere, so it's OK to remove for now. Supporting Wheezy will likely complicate the role unnecessarily—can discuss in #33.

Still need to repeat the build-and-install process for stable kernels.

**Comment by garrettr** [comment]
@conorsch This merge targets develop, which will be incorrect after merging https://github.com/freedomofpress/grsec/pull/35. Should we just re-submit this PR to target master once #35 is merged?

**Comment by conorsch** [comment]
@garrettr Yes, let's merge #35 first and then resubmit this PR targeting `master`. After more testing I'll add a commit or two to this branch, so we have the review and discussion in one place.

**Comment by ageis** [comment]
Jesus. kernel-image depends on docbook-utils depends on jadetext depends on texlive-latex-base. It's even installing the Lynx browser and crap for rendering SGML. how dumb!

**Comment by garrettr** [comment]
Maybe we should file an upstream issue for this. It certainly seems like a bug. I assume those deps are needed to build documentation, but it's annoying to pull them in when all you want is to build a kernel.

**Comment by conorsch** [comment]
OK, built a 3.x kernel in Vagrant under Vivid and successfully installed on:
- `ubuntu/trusty64`
- `ubuntu/vivid64`
- `debian/wheezy64`
- `debian/jessie64`

I'm happy with the fix as present in this PR. Postponing merge until #34 is resolved, in case we need to rebase.

**Comment by conorsch** [comment]
Superseded by #36.

**Pull request closed without merging**
