### PR TITLE
Convert metapackage build process from Bash script to Ansible tasks

### PR DESCRIPTION
**Pull request by conorsch**
Also using default vars to write to the template file, which should simplify version bumps.

### CODE REVIEW

**Comment by garrettr** [comment]
I like everything about this. :+1:

**Comment by conorsch** [comment]
@garrett Good, hopefully it becomes a timesaver. Note that the default variable for the version of SecureDrop is `0.3`. You can pass in a more specific version via `--extra-args securedrop_version="0.3.4"`, but maybe it makes more sense to default to whatever the newest version is. The `0.3` was copied over from the Bash script, but the Bash script also checked `$1` for the new version.

**Comment by garrettr** [comment]
Yeah, I'd bump that to 0.3.4 or even 0.3.5 since we're about to release 0.3.5 and this is on develop.

**Comment by conorsch** [comment]
Done. Note that the kernel-building role doesn't currently work on develop, due to #10. Will take a crack at that soon.

**Pull request merged**
